### ISSUE TITLE
Consider exposing $scope.network..

### ISSUE THREAD

**Issue by grtjn** [patrickmcelwee/ml-visjs-graph-ng#11]
I wanted to get hands on the graph selection. Easiest was to expose `$scope.network`, and using `getSelection()` on that.

**Comment by patrickmcelwee** [comment]
How did you do this?

**Comment by grtjn** [comment]
I had exposed both items and network as an optional bidirectional property of the directive:

```
        items: '=?',
        network: '=?'
```

And added this to the controller:

```
    ctrl.graphEvents = {
      onload: function(network) {
        $scope.network = network;
      },
```

(items are already exposed on $scope)
