### ISSUE TITLE
Don't hard-wire the service into the ctrl

### ISSUE THREAD

**Issue by grtjn** [patrickmcelwee/ml-visjs-graph-ng#3]
Instead, pass through a service via the directive, so that people can provide their own service if they like. You can make life easy for end users by adding a service factory that comes with one or more predefined ones that can be patched to need.

See also ml-synonyms-ng. I use a similar approach there..

**Comment by patrickmcelwee** [comment]
@grtjn, have a moment to take a look at PR https://github.com/patrickmcelwee/ml-visjs-graph-ng/issues/4 for a sanity check?
